version: "3.9"

services:
  # React Frontend Application (Development)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL_1=http://localhost:4001
      - VITE_API_URL_2=http://localhost:4002
    depends_on:
      - server1
      - server2
    networks:
      - employee-network

  # JSON Server 1 (Departments & Basic Info)
  server1:
    image: node:20-alpine
    working_dir: /app
    command: npx json-server --watch db-step1.json --host 0.0.0.0 --port 4001 --delay 3000
    volumes:
      - ./db-step1.json:/app/db-step1.json
    ports:
      - "4001:4001"
    networks:
      - employee-network

  # JSON Server 2 (Locations & Details)
  server2:
    image: node:20-alpine
    working_dir: /app
    command: npx json-server --watch db-step2.json --host 0.0.0.0 --port 4002 --delay 3000
    volumes:
      - ./db-step2.json:/app/db-step2.json
    ports:
      - "4002:4002"
    networks:
      - employee-network

networks:
  employee-network:
    driver: bridge
